### ISSUE TITLE
Allow passing configuration information to mypy

### ISSUE THREAD

**Issue by eyurtsev** [geo7/mypy_clean_slate#105]
Thank you for writing this code!

I cloned and ran it without the --strict flag! This was used to generate this PR: https://github.com/langchain-ai/langchain/pull/18753/files

We're having trouble just bumping to a newer version of mypy even without the strict mode, would be helpful if we could configure options a bit :)

**Comment by geo7** [comment]
@eyurtsev :wave: ah nice, glad it was useful :)  And thanks for linking the PR. Having the ability to alter the params mypy uses makes sense, `--strict` isn't always going to be possible :sweat_smile: 

Just thinking about a nice approach for this - let me know if you've any thoughts - otherwise I'll have a prod  and see what works.
